const words = [
    {"番号": 1, "英語": "彼女の助言に従う", "日本語": "follow her advice"},
    {"番号": 2, "英語": "真剣にその問題を考える", "日本語": "consider the problem seriously"},
    {"番号": 3, "英語": "20%増加する", "日本語": "increase by 20%"},
    {"番号": 4, "英語": "君がすぐ来ることを予期する", "日本語": "expect you to arrive soon"},
    {"番号": 5, "英語": "真実を語る決意をする", "日本語": "decide to tell the truth"},
    {"番号": 6, "英語": "特異な能力を発達させる", "日本語": "develop a unique ability"},
    {"番号": 7, "英語": "彼に情報を与える", "日本語": "provide him with information"},
    {"番号": 8, "英語": "急速に成長し続ける", "日本語": "continue to grow fast"},
    {"番号": 9, "英語": "リストは彼の名前を含んでいる", "日本語": "The list includes his name."},
    {"番号": 10, "英語": "黙ったままでいる", "日本語": "remain silent"},
    {"番号": 11, "英語": "山頂に達する", "日本語": "reach the mountain top"},
    {"番号": 12, "英語": "彼に外出を許可する", "日本語": "allow him to go out"},
    {"番号": 13, "英語": "働くよう強制される", "日本語": "be forced to work"},
    {"番号": 14, "英語": "貧しい人に援助を申し出る", "日本語": "offer help to the poor"},
    {"番号": 15, "英語": "間違いを悟る", "日本語": "realize the error"},
    {"番号": 16, "英語": "新しいやり方を提案する", "日本語": "suggest a new way"},
    {"番号": 17, "英語": "もっと注意を必要とする", "日本語": "require more attention"},
    {"番号": 18, "英語": "お金のことを心配する", "日本語": "worry about money"},
    {"番号": 19, "英語": "彼はどこに行ったのかと思う", "日本語": "wonder where he has gone"},
    {"番号": 20, "英語": "その車には5万ドルかかった", "日本語": "The car cost me $50,000."},
    {"番号": 21, "英語": "腹を立てがちである", "日本語": "tend to get angry"},
    {"番号": 22, "英語": "すべては彼しだいだ", "日本語": "Everything depends on him."},
    {"番号": 23, "英語": "友人と部屋を共有する", "日本語": "share a room with a friend"},
    {"番号": 24, "英語": "もっと自由を要求する", "日本語": "demand more freedom"},
    {"番号": 25, "英語": "大統領を支持する", "日本語": "support the President"},
    {"番号": 26, "英語": "多くの若者を雇う", "日本語": "hire many young people"},
    {"番号": 27, "英語": "彼を友達とみなす", "日本語": "regard him as a friend"},
    {"番号": 28, "英語": "この話は事実に基づいている", "日本語": "This story is based on fact."},
    {"番号": 29, "英語": "生活状態を向上させる", "日本語": "improve living conditions"},
    {"番号": 30, "英語": "重要性を認める", "日本語": "recognize the importance"},
    {"番号": 31, "英語": "色彩の変化に気付く", "日本語": "notice the color change"},
    {"番号": 32, "英語": "シートベルトを締めることになっている", "日本語": "You are supposed to wear a seat belt. "},
    {"番号": 33, "英語": "両手を上げる", "日本語": "raise both hands"},
    {"番号": 34, "英語": "コーヒーよりお茶を好む", "日本語": "prefer tea to coffee"},
    {"番号": 35, "英語": "患者を元気づける", "日本語": "cheer up the patients"},
    {"番号": 36, "英語": "ひどい損害を受ける", "日本語": "suffer heavy damage"},
    {"番号": 37, "英語": "なくしたバッグの特徴を言う", "日本語": "describe the lost bag"},
    {"番号": 38, "英語": "彼が眠るのをさまげる", "日本語": "prevent him from sleeping"},
    {"番号": 39, "英語": "エネルギー費を減らす", "日本語": "reduce energy costs"},
    {"番号": 40, "英語": "塩と砂糖をまちがえる", "日本語": "mistake salt for sugar"},
    {"番号": 41, "英語": "客のために部屋を準備する", "日本語": "prepare a room for a guest"},
    {"番号": 42, "英語": "子供に読書をすすめる", "日本語": "encourage children to read"},
    {"番号": 43, "英語": "本当だとわかる", "日本語": "prove to be true"},
    {"番号": 44, "英語": "子供みたいに彼をあつかう", "日本語": "treat him like a child"},
    {"番号": 45, "英語": "会社を設立する", "日本語": "establish a company"},
    {"番号": 46, "英語": "ストレスと関係のある病気", "日本語": "stress-related illness"},
    {"番号": 47, "英語": "日本と中国を比較する", "日本語": "compare Japan with China"},
    {"番号": 48, "英語": "テーブルクロスを広げる", "日本語": "spread the tablecloth"},
    {"番号": 49, "英語": "この語は何を指示するか", "日本語": "What does this word refer to?"},
    {"番号": 50, "英語": "その都市に水を供給する", "日本語": "supply the city with water"},
    {"番号": 51, "英語": "有益な知識を得る", "日本語": "gain useful knowledge"},
    {"番号": 52, "英語": "森林を破壊する", "日本語": "destroy forests"},
    {"番号": 53, "英語": "全ての場合に規則を当てはめる", "日本語": "apply the rule to every case"},
    {"番号": 54, "英語": "警官に助けを求める", "日本語": "seek help from the police"},
    {"番号": 55, "英語": "盗難車を捜す", "日本語": "search for the stolen car"},
    {"番号": 56, "英語": "彼はUFOを見たと主張する", "日本語": "He claims that he saw a UFO."},
    {"番号": 57, "英語": "地図を描く", "日本語": "draw a map"},
    {"番号": 58, "英語": "希望を捨てるのを拒む", "日本語": "refuse to give up hope"},
    {"番号": 59, "英語": "質問に答える", "日本語": "respond to question"},
    {"番号": 60, "英語": "二度とそのことを口にするな", "日本語": "Never mention it again."},
    {"番号": 61, "英語": "人を外見で判断する", "日本語": "judge a person by his looks"},
    {"番号": 62, "英語": "飛行機はシカゴに接近している", "日本語": "The plane is approaching Chicago."},
    {"番号": 63, "英語": "自分が間違っていたと認める", "日本語": "I admit that I was wrong."},
    {"番号": 64, "英語": "時代の気分を反映する", "日本語": "reflect the mood of the times"},
    {"番号": 65, "英語": "仕事を遂行する", "日本語": "perform the job"},
    {"番号": 66, "英語": "すごく退屈な映画", "日本語": "a very boring movie"},
    {"番号": 67, "英語": "ジャングルで生き残る", "日本語": "survive in the jungle"},
    {"番号": 68, "英語": "言葉は考えを表す", "日本語": "Words represent ideas."},
    {"番号": 69, "英語": "彼は正しいと主張する", "日本語": "argue that he is right"},
    {"番号": 70, "英語": "自由を当然と考える", "日本語": "take freedom for granted"},
    {"番号": 71, "英語": "データは彼が正しいことを示す", "日本語": "The data indicate that he is right."},
    {"番号": 72, "英語": "その本はハワードのものだ", "日本語": "The book belongs to Howard."},
    {"番号": 73, "英語": "言語を習得する", "日本語": "acquire a language"},
    {"番号": 74, "英語": "彼の手紙に返事をする", "日本語": "reply to his letter"},
    {"番号": 75, "英語": "大勢の家族を養う", "日本語": "feed a large family"},
    {"番号": 76, "英語": "現実から逃避する", "日本語": "escape from reality"},
    {"番号": 77, "英語": "古い制度に取って代わる", "日本語": "replace the old system"},
    {"番号": 78, "英語": "驚くべき事実を明らかにする", "日本語": "reveal a surprising fact"},
    {"番号": 79, "英語": "日本は海に囲まれている", "日本語": "Japan is surrounded by the sea."},
    {"番号": 80, "英語": "その仕事は君に合っている", "日本語": "The job suits you."},
    {"番号": 81, "英語": "日本の推定人口", "日本語": "the estimated population of Japan"},
    {"番号": 82, "英語": "アジア市場をねらう", "日本語": "aim at the Asian market"},
    {"番号": 83, "英語": "家族くのためにお金をかせぐ", "日本語": "earn money for the family"},
    {"番号": 84, "英語": "記憶力が低下し始めた", "日本語": "My memory began to decline."},
    {"番号": 85, "英語": "フォードを買う余裕が無い", "日本語": "can't afford to buy a Ford"},
    {"番号": 86, "英語": "彼女の怒りに当惑する", "日本語": "be confused by her anger"},
    {"番号": 87, "英語": "高校を卒業する", "日本語": "graduate from high school"},
    {"番号": 88, "英語": "国によって変わる", "日本語": "vary from country to country"},
    {"番号": 89, "英語": "カバーを取り除く", "日本語": "remove the cover"},
    {"番号": 90, "英語": "フランスへ行くと言い張る", "日本語": "insist on going to France"},
    {"番号": 91, "英語": "あらゆる記録を調べる", "日本語": "examine every record"},
    {"番号": 92, "英語": "彼に約束を思い出させる", "日本語": "remind him of the promise"},
    {"番号": 93, "英語": "世界平和に貢献する", "日本語": "contribute to world peace"},
    {"番号": 94, "英語": "彼に危険を警告する", "日本語": "warn him of the danger"},
    {"番号": 95, "英語": "コンピューターをインターネットにつなぐ", "日本語": "connect the computer to the Internet"},
    {"番号": 96, "英語": "力で彼に匹敵する", "日本語": "match him in power"},
    {"番号": 97, "英語": "その問題に焦点を合わせる", "日本語": "focus on the problem"},
    {"番号": 98, "英語": "提案を拒否する", "日本語": "reject the proposal"},
    {"番号": 99, "英語": "それは本当だと彼に確信させる", "日本語": "convince him that it is true"},
    {"番号": 100, "英語": "健康は幸福と関連している", "日本語": "Health is associated with happiness."},
    {"番号": 101, "英語": "病院へ急いでいく", "日本語": "rush into the hospital"},
    {"番号": 102, "英語": "情報の必要性を強調する", "日本語": "stress the need for information"},
    {"番号": 103, "英語": "彼の注意を引きつける", "日本語": "attract his attention"},
    {"番号": 104, "英語": "彼らの力に頼る", "日本語": "rely on their power"},
    {"番号": 105, "英語": "家を出たのを後悔する", "日本語": "regret leaving home"},
    {"番号": 106, "英語": "新しいシステムを採用する", "日本語": "adopt a new system"},
    {"番号": 107, "英語": "ビンをよく振る", "日本語": "shake the bottle well"},
    {"番号": 108, "英語": "彼女の気持ちを傷つける", "日本語": "hurt her feelings"},
    {"番号": 109, "英語": "マウスでコンピューターを操作する", "日本語": "operate a computer with a mouse"},
    {"番号": 110, "英語": "運動は寿命を延ばす", "日本語": "Exercise extends life."},
    {"番号": 111, "英語": "失敗を他人のせいにする", "日本語": "blame others for the failure"},
    {"番号": 112, "英語": "その本は6課で構成されている", "日本語": "The book consists of six lessons."},
    {"番号": 113, "英語": "彼らを説得して帰らせる", "日本語": "persuade them to go back"},
    {"番号": 114, "英語": "彼女の仕事に感嘆する", "日本語": "admire her work"},
    {"番号": 115, "英語": "試験の結果に失望する", "日本語": "be disappointed with the test results"},
    {"番号": 116, "英語": "市場を拡大する", "日本語": "expand the market"},
    {"番号": 117, "英語": "森林を保護する", "日本語": "preserve forests"},
    {"番号": 118, "英語": "自由になろうともがく", "日本語": "struggle to get free"},
    {"番号": 119, "英語": "会議の手はずを整える", "日本語": "arrange the meeting"},
    {"番号": 120, "英語": "彼の睡眠をさまたげる", "日本語": "disturb his sleep"},
    {"番号": 121, "英語": "外国人労働者を雇う", "日本語": "employ foreign workers"},
    {"番号": 122, "英語": "ボランティア活動に従事する", "日本語": "engage in volunteer activities"},
    {"番号": 123, "英語": "捨てられたペット", "日本語": "an abandoned pet"},
    {"番号": 124, "英語": "価格を示す", "日本語": "display prices"},
    {"番号": 125, "英語": "数々の困難に出会う", "日本語": "encounter many difficulties"},
    {"番号": 126, "英語": "冗談で学生を笑わせる", "日本語": "amuse students with jokes"},
    {"番号": 127, "英語": "おじゃましてすいませんが…", "日本語": "Sorry to bother you, but …"},
    {"番号": 128, "英語": "彼の話に集中する", "日本語": "concentrate on what he is saying"},
    {"番号": 129, "英語": "新しい文化に適応する", "日本語": "adapt to a new culture"},
    {"番号": 130, "英語": "その問題に頭を悩ませる", "日本語": "be puzzled by the problem"},
    {"番号": 131, "英語": "彼の感情に訴えかける", "日本語": "appeal to his feelings"},
    {"番号": 132, "英語": "歌と踊りを結合させる", "日本語": "combine song and dance"},
    {"番号": 133, "英語": "彼の到着を遅らせる", "日本語": "delay his arrival"},
    {"番号": 134, "英語": "車を修理する", "日本語": "repair the car"},
    {"番号": 135, "英語": "夢中にさせる物語", "日本語": "a fascinating story"},
    {"番号": 136, "英語": "ごめんなさい", "日本語": "Pardon me."},
    {"番号": 137, "英語": "海外から食料を輸入する", "日本語": "import food from abroad"},
    {"番号": 138, "英語": "彼は親切だと述べる", "日本語": "remark that he is kind"},
    {"番号": 139, "英語": "ホテルの部屋を予約する", "日本語": "reserve a room at a hotel"},
    {"番号": 140, "英語": "驚異的な早さで", "日本語": "at an amazing speed"},
    {"番号": 141, "英語": "ぞっとするような経験", "日本語": "frightening experiences"},
    {"番号": 142, "英語": "仕事から彼を解放する", "日本語": "release him from work"},
    {"番号": 143, "英語": "アパートを借りる", "日本語": "rent an apartment"},
    {"番号": 144, "英語": "病気から回復する", "日本語": "recover from illness"},
    {"番号": 145, "英語": "彼をスパイではないかと疑う", "日本語": "suspect him of being a spy"},
    {"番号": 146, "英語": "友人に伝言を渡す", "日本語": "deliver a message to a friend"},
    {"番号": 147, "英語": "目で人の本人確認をする", "日本語": "identify people by their eyes"},
    {"番号": 148, "英語": "オフィスはその地域にある", "日本語": "The office is located in the area."},
    {"番号": 149, "英語": "車を製造する会社", "日本語": "a car manufacturing company"},
    {"番号": 150, "英語": "高い地位を占める", "日本語": "occupy a high position"},
    {"番号": 151, "英語": "家を所有する", "日本語": "own a house"},
    {"番号": 152, "英語": "危険にさらされている", "日本語": "be exposed to danger"},
    {"番号": 153, "英語": "小説を英語に翻訳する", "日本語": "translate a novel into English"},
    {"番号": 154, "英語": "彼の病気を治す", "日本語": "cure him of his illness"},
    {"番号": 155, "英語": "危険に気付く", "日本語": "perceive danger"},
    {"番号": 156, "英語": "新しい学校に慣れる", "日本語": "adjust to a new school"},
    {"番号": 157, "英語": "その音にぎょっとする", "日本語": "be alarmed by the noise"},
    {"番号": 158, "英語": "彼の仕事を手伝う", "日本語": "assist him in his work"},
    {"番号": 159, "英語": "凍った小川", "日本語": "a frozen stream"},
    {"番号": 160, "英語": "パーティを台無しにする", "日本語": "spoil the party"},
    {"番号": 161, "英語": "ギアを変える", "日本語": "shift gears"},
    {"番号": 162, "英語": "そもまちがいには恥ずかしい", "日本語": "be embarrassed by the mistake"},
    {"番号": 163, "英語": "二人の結婚を承認する", "日本語": "approve of their marriage"},
    {"番号": 164, "英語": "65キログラムの重さがある", "日本語": "weight 65 kilograms"},
    {"番号": 165, "英語": "足を広げる", "日本語": "stretch my legs"},
    {"番号": 166, "英語": "会議に参加する", "日本語": "participate in the meeting"},
    {"番号": 167, "英語": "ピカソの作品を展示する", "日本語": "exhibit Picasso's works"},
    {"番号": 168, "英語": "私の成功はあなたのおかげだ", "日本語": "I owe my success to you."},
    {"番号": 169, "英語": "彼の誕生日を祝う", "日本語": "celebrate his birthday"},
    {"番号": 170, "英語": "電球で飾られた木々", "日本語": "trees decorated with lights"},
    {"番号": 171, "英語": "彼の遅刻を許す", "日本語": "forgive him for being late"},
    {"番号": 172, "英語": "ベンチで座っている", "日本語": "be seated on the bench"},
    {"番号": 173, "英語": "その事故で負傷する", "日本語": "be injured in the accident"},
    {"番号": 174, "英語": "ウエディングドレスを縫う", "日本語": "sew a wedding dress"},
    {"番号": 175, "英語": "テストの結果", "日本語": "the result of the test"},
    {"番号": 176, "英語": "人類の言語の特徴", "日本語": "features of human language"},
    {"番号": 177, "英語": "現代社会の問題", "日本語": "the problems of modern society"},
    {"番号": 178, "英語": "水車", "日本語": "a water wheel"},
    {"番号": 179, "英語": "教育に高い価値を置く", "日本語": "put a high value on education"},
    {"番号": 180, "英語": "二酸化炭素の温室効果", "日本語": "the greenhouse effect of CO2"},
  ];