const words = [
  {"番号": 1, "英語": "彼女の助言に従う", "日本語": "follow her advice"},
  {"番号": 2, "英語": "真剣にその問題を考える", "日本語": "consider the problem seriously"},
  {"番号": 3, "英語": "20%増加する", "日本語": "increase by 20%"},
  {"番号": 4, "英語": "君がすぐ来ることを予期する", "日本語": "expect you to arrive soon"},
  {"番号": 5, "英語": "真実を語る決意をする", "日本語": "decide to tell the truth"},
  {"番号": 6, "英語": "特異な能力を発達させる", "日本語": "develop a unique ability"},
  {"番号": 7, "英語": "彼に情報を与える", "日本語": "provide him with information"},
  {"番号": 8, "英語": "急速に成長し続ける", "日本語": "continue to grow fast"},
  {"番号": 9, "英語": "リストは彼の名前を含んでいる", "日本語": "The list includes his name."},
  {"番号": 10, "英語": "黙ったままでいる", "日本語": "remain silent"},
  {"番号": 11, "英語": "山頂に達する", "日本語": "reach the mountain top"},
  {"番号": 12, "英語": "彼に外出を許可する", "日本語": "allow him to go out"},
  {"番号": 13, "英語": "働くよう強制される", "日本語": "be forced to work"},
  {"番号": 14, "英語": "貧しい人に援助を申し出る", "日本語": "offer help to the poor"},
  {"番号": 15, "英語": "間違いを悟る", "日本語": "realize the error"},
  {"番号": 16, "英語": "新しいやり方を提案する", "日本語": "suggest a new way"},
  {"番号": 17, "英語": "もっと注意を必要とする", "日本語": "require more attention"},
  {"番号": 18, "英語": "お金のことを心配する", "日本語": "worry about money"},
  {"番号": 19, "英語": "彼はどこに行ったのかと思う", "日本語": "wonder where he has gone"},
  {"番号": 20, "英語": "その車には5万ドルかかった", "日本語": "The car cost me $50,000."},
  {"番号": 21, "英語": "腹を立てがちである", "日本語": "tend to get angry"},
  {"番号": 22, "英語": "すべては彼しだいだ", "日本語": "Everything depends on him."},
  {"番号": 23, "英語": "友人と部屋を共有する", "日本語": "share a room with a friend"},
  {"番号": 24, "英語": "もっと自由を要求する", "日本語": "demand more freedom"},
  {"番号": 25, "英語": "大統領を支持する", "日本語": "support the President"},
  {"番号": 26, "英語": "多くの若者を雇う", "日本語": "hire many young people"},
  {"番号": 27, "英語": "彼を友達とみなす", "日本語": "regard him as a friend"},
  {"番号": 28, "英語": "この話は事実に基づいている", "日本語": "This story is based on fact."},
  {"番号": 29, "英語": "生活状態を向上させる", "日本語": "improve living conditions"},
  {"番号": 30, "英語": "重要性を認める", "日本語": "recognize the importance"},
  {"番号": 31, "英語": "色彩の変化に気付く", "日本語": "notice the color change"},
  {"番号": 32, "英語": "シートベルトを締めることになっている", "日本語": "You are supposed to wear a seat belt. "},
  {"番号": 33, "英語": "両手を上げる", "日本語": "raise both hands"},
  {"番号": 34, "英語": "コーヒーよりお茶を好む", "日本語": "prefer tea to coffee"},
  {"番号": 35, "英語": "患者を元気づける", "日本語": "cheer up the patients"},
  {"番号": 36, "英語": "ひどい損害を受ける", "日本語": "suffer heavy damage"},
  {"番号": 37, "英語": "なくしたバッグの特徴を言う", "日本語": "describe the lost bag"},
  {"番号": 38, "英語": "彼が眠るのをさまげる", "日本語": "prevent him from sleeping"},
  {"番号": 39, "英語": "エネルギー費を減らす", "日本語": "reduce energy costs"},
  {"番号": 40, "英語": "塩と砂糖をまちがえる", "日本語": "mistake salt for sugar"},
  {"番号": 41, "英語": "客のために部屋を準備する", "日本語": "prepare a room for a guest"},
  {"番号": 42, "英語": "子供に読書をすすめる", "日本語": "encourage children to read"},
  {"番号": 43, "英語": "本当だとわかる", "日本語": "prove to be true"},
  {"番号": 44, "英語": "子供みたいに彼をあつかう", "日本語": "treat him like a child"},
  {"番号": 45, "英語": "会社を設立する", "日本語": "establish a company"},
  {"番号": 46, "英語": "ストレスと関係のある病気", "日本語": "stress-related illness"},
  {"番号": 47, "英語": "日本と中国を比較する", "日本語": "compare Japan with China"},
  {"番号": 48, "英語": "テーブルクロスを広げる", "日本語": "spread the tablecloth"},
  {"番号": 49, "英語": "この語は何を指示するか", "日本語": "What does this word refer to?"},
  {"番号": 50, "英語": "その都市に水を供給する", "日本語": "supply the city with water"},
  {"番号": 51, "英語": "有益な知識を得る", "日本語": "gain useful knowledge"},
  {"番号": 52, "英語": "森林を破壊する", "日本語": "destroy forests"},
  {"番号": 53, "英語": "全ての場合に規則を当てはめる", "日本語": "apply the rule to every case"},
  {"番号": 54, "英語": "警官に助けを求める", "日本語": "seek help from the police"},
  {"番号": 55, "英語": "盗難車を捜す", "日本語": "search for the stolen car"},
  {"番号": 56, "英語": "彼はUFOを見たと主張する", "日本語": "He claims that he saw a UFO."},
  {"番号": 57, "英語": "地図を描く", "日本語": "draw a map"},
  {"番号": 58, "英語": "希望を捨てるのを拒む", "日本語": "refuse to give up hope"},
  {"番号": 59, "英語": "質問に答える", "日本語": "respond to question"},
  {"番号": 60, "英語": "二度とそのことを口にするな", "日本語": "Never mention it again."},
  {"番号": 61, "英語": "人を外見で判断する", "日本語": "judge a person by his looks"},
  {"番号": 62, "英語": "飛行機はシカゴに接近している", "日本語": "The plane is approaching Chicago."},
  {"番号": 63, "英語": "自分が間違っていたと認める", "日本語": "I admit that I was wrong."},
  {"番号": 64, "英語": "時代の気分を反映する", "日本語": "reflect the mood of the times"},
  {"番号": 65, "英語": "仕事を遂行する", "日本語": "perform the job"},
  {"番号": 66, "英語": "すごく退屈な映画", "日本語": "a very boring movie"},
  {"番号": 67, "英語": "ジャングルで生き残る", "日本語": "survive in the jungle"},
  {"番号": 68, "英語": "言葉は考えを表す", "日本語": "Words represent ideas."},
  {"番号": 69, "英語": "彼は正しいと主張する", "日本語": "argue that he is right"},
  {"番号": 70, "英語": "自由を当然と考える", "日本語": "take freedom for granted"},
  {"番号": 71, "英語": "データは彼が正しいことを示す", "日本語": "The data indicate that he is right."},
  {"番号": 72, "英語": "その本はハワードのものだ", "日本語": "The book belongs to Howard."},
  {"番号": 73, "英語": "言語を習得する", "日本語": "acquire a language"},
  {"番号": 74, "英語": "彼の手紙に返事をする", "日本語": "reply to his letter"},
  {"番号": 75, "英語": "大勢の家族を養う", "日本語": "feed a large family"},
  {"番号": 76, "英語": "現実から逃避する", "日本語": "escape from reality"},
  {"番号": 77, "英語": "古い制度に取って代わる", "日本語": "replace the old system"},
  {"番号": 78, "英語": "驚くべき事実を明らかにする", "日本語": "reveal a surprising fact"},
  {"番号": 79, "英語": "日本は海に囲まれている", "日本語": "Japan is surrounded by the sea."},
  {"番号": 80, "英語": "その仕事は君に合っている", "日本語": "The job suits you."},
  {"番号": 81, "英語": "日本の推定人口", "日本語": "the estimated population of Japan"},
  {"番号": 82, "英語": "アジア市場をねらう", "日本語": "aim at the Asian market"},
  {"番号": 83, "英語": "家族くのためにお金をかせぐ", "日本語": "earn money for the family"},
  {"番号": 84, "英語": "記憶力が低下し始めた", "日本語": "My memory began to decline."},
  {"番号": 85, "英語": "フォードを買う余裕が無い", "日本語": "can't afford to buy a Ford"},
  {"番号": 86, "英語": "彼女の怒りに当惑する", "日本語": "be confused by her anger"},
  {"番号": 87, "英語": "高校を卒業する", "日本語": "graduate from high school"},
  {"番号": 88, "英語": "国によって変わる", "日本語": "vary from country to country"},
  {"番号": 89, "英語": "カバーを取り除く", "日本語": "remove the cover"},
  {"番号": 90, "英語": "フランスへ行くと言い張る", "日本語": "insist on going to France"},
  {"番号": 91, "英語": "あらゆる記録を調べる", "日本語": "examine every record"},
  {"番号": 92, "英語": "彼に約束を思い出させる", "日本語": "remind him of the promise"},
  {"番号": 93, "英語": "世界平和に貢献する", "日本語": "contribute to world peace"},
  {"番号": 94, "英語": "彼に危険を警告する", "日本語": "warn him of the danger"},
  {"番号": 95, "英語": "コンピューターをインターネットにつなぐ", "日本語": "connect the computer to the Internet"},
  {"番号": 96, "英語": "力で彼に匹敵する", "日本語": "match him in power"},
  {"番号": 97, "英語": "その問題に焦点を合わせる", "日本語": "focus on the problem"},
  {"番号": 98, "英語": "提案を拒否する", "日本語": "reject the proposal"},
  {"番号": 99, "英語": "それは本当だと彼に確信させる", "日本語": "convince him that it is true"},
  {"番号": 100, "英語": "健康は幸福と関連している", "日本語": "Health is associated with happiness."},
  {"番号": 101, "英語": "病院へ急いでいく", "日本語": "rush into the hospital"},
  {"番号": 102, "英語": "情報の必要性を強調する", "日本語": "stress the need for information"},
  {"番号": 103, "英語": "彼の注意を引きつける", "日本語": "attract his attention"},
  {"番号": 104, "英語": "彼らの力に頼る", "日本語": "rely on their power"},
  {"番号": 105, "英語": "家を出たのを後悔する", "日本語": "regret leaving home"},
  {"番号": 106, "英語": "新しいシステムを採用する", "日本語": "adopt a new system"},
  {"番号": 107, "英語": "ビンをよく振る", "日本語": "shake the bottle well"},
  {"番号": 108, "英語": "彼女の気持ちを傷つける", "日本語": "hurt her feelings"},
  {"番号": 109, "英語": "マウスでコンピューターを操作する", "日本語": "operate a computer with a mouse"},
  {"番号": 110, "英語": "運動は寿命を延ばす", "日本語": "Exercise extends life."},
  {"番号": 111, "英語": "失敗を他人のせいにする", "日本語": "blame others for the failure"},
  {"番号": 112, "英語": "その本は6課で構成されている", "日本語": "The book consists of six lessons."},
  {"番号": 113, "英語": "彼らを説得して帰らせる", "日本語": "persuade them to go back"},
  {"番号": 114, "英語": "彼女の仕事に感嘆する", "日本語": "admire her work"},
  {"番号": 115, "英語": "試験の結果に失望する", "日本語": "be disappointed with the test results"},
  {"番号": 116, "英語": "市場を拡大する", "日本語": "expand the market"},
  {"番号": 117, "英語": "森林を保護する", "日本語": "preserve forests"},
  {"番号": 118, "英語": "自由になろうともがく", "日本語": "struggle to get free"},
  {"番号": 119, "英語": "会議の手はずを整える", "日本語": "arrange the meeting"},
  {"番号": 120, "英語": "彼の睡眠をさまたげる", "日本語": "disturb his sleep"},
  {"番号": 121, "英語": "外国人労働者を雇う", "日本語": "employ foreign workers"},
  {"番号": 122, "英語": "ボランティア活動に従事する", "日本語": "engage in volunteer activities"},
  {"番号": 123, "英語": "捨てられたペット", "日本語": "an abandoned pet"},
  {"番号": 124, "英語": "価格を示す", "日本語": "display prices"},
  {"番号": 125, "英語": "数々の困難に出会う", "日本語": "encounter many difficulties"},
  {"番号": 126, "英語": "冗談で学生を笑わせる", "日本語": "amuse students with jokes"},
  {"番号": 127, "英語": "おじゃましてすいませんが…", "日本語": "Sorry to bother you, but …"},
  {"番号": 128, "英語": "彼の話に集中する", "日本語": "concentrate on what he is saying"},
  {"番号": 129, "英語": "新しい文化に適応する", "日本語": "adapt to a new culture"},
  {"番号": 130, "英語": "その問題に頭を悩ませる", "日本語": "be puzzled by the problem"},
  {"番号": 131, "英語": "彼の感情に訴えかける", "日本語": "appeal to his feelings"},
  {"番号": 132, "英語": "歌と踊りを結合させる", "日本語": "combine song and dance"},
  {"番号": 133, "英語": "彼の到着を遅らせる", "日本語": "delay his arrival"},
  {"番号": 134, "英語": "車を修理する", "日本語": "repair the car"},
  {"番号": 135, "英語": "夢中にさせる物語", "日本語": "a fascinating story"},
  {"番号": 136, "英語": "ごめんなさい", "日本語": "Pardon me."},
  {"番号": 137, "英語": "海外から食料を輸入する", "日本語": "import food from abroad"},
  {"番号": 138, "英語": "彼は親切だと述べる", "日本語": "remark that he is kind"},
  {"番号": 139, "英語": "ホテルの部屋を予約する", "日本語": "reserve a room at a hotel"},
  {"番号": 140, "英語": "驚異的な早さで", "日本語": "at an amazing speed"},
  {"番号": 141, "英語": "ぞっとするような経験", "日本語": "frightening experiences"},
  {"番号": 142, "英語": "仕事から彼を解放する", "日本語": "release him from work"},
  {"番号": 143, "英語": "アパートを借りる", "日本語": "rent an apartment"},
  {"番号": 144, "英語": "病気から回復する", "日本語": "recover from illness"},
  {"番号": 145, "英語": "彼をスパイではないかと疑う", "日本語": "suspect him of being a spy"},
  {"番号": 146, "英語": "友人に伝言を渡す", "日本語": "deliver a message to a friend"},
  {"番号": 147, "英語": "目で人の本人確認をする", "日本語": "identify people by their eyes"},
  {"番号": 148, "英語": "オフィスはその地域にある", "日本語": "The office is located in the area."},
  {"番号": 149, "英語": "車を製造する会社", "日本語": "a car manufacturing company"},
  {"番号": 150, "英語": "高い地位を占める", "日本語": "occupy a high position"},
  {"番号": 151, "英語": "家を所有する", "日本語": "own a house"},
  {"番号": 152, "英語": "危険にさらされている", "日本語": "be exposed to danger"},
  {"番号": 153, "英語": "小説を英語に翻訳する", "日本語": "translate a novel into English"},
  {"番号": 154, "英語": "彼の病気を治す", "日本語": "cure him of his illness"},
  {"番号": 155, "英語": "危険に気付く", "日本語": "perceive danger"},
  {"番号": 156, "英語": "新しい学校に慣れる", "日本語": "adjust to a new school"},
  {"番号": 157, "英語": "その音にぎょっとする", "日本語": "be alarmed by the noise"},
  {"番号": 158, "英語": "彼の仕事を手伝う", "日本語": "assist him in his work"},
  {"番号": 159, "英語": "凍った小川", "日本語": "a frozen stream"},
  {"番号": 160, "英語": "パーティを台無しにする", "日本語": "spoil the party"},
  {"番号": 161, "英語": "ギアを変える", "日本語": "shift gears"},
  {"番号": 162, "英語": "そもまちがいには恥ずかしい", "日本語": "be embarrassed by the mistake"},
  {"番号": 163, "英語": "二人の結婚を承認する", "日本語": "approve of their marriage"},
  {"番号": 164, "英語": "65キログラムの重さがある", "日本語": "weight 65 kilograms"},
  {"番号": 165, "英語": "足を広げる", "日本語": "stretch my legs"},
  {"番号": 166, "英語": "会議に参加する", "日本語": "participate in the meeting"},
  {"番号": 167, "英語": "ピカソの作品を展示する", "日本語": "exhibit Picasso's works"},
  {"番号": 168, "英語": "私の成功はあなたのおかげだ", "日本語": "I owe my success to you."},
  {"番号": 169, "英語": "彼の誕生日を祝う", "日本語": "celebrate his birthday"},
  {"番号": 170, "英語": "電球で飾られた木々", "日本語": "trees decorated with lights"},
  {"番号": 171, "英語": "彼の遅刻を許す", "日本語": "forgive him for being late"},
  {"番号": 172, "英語": "ベンチで座っている", "日本語": "be seated on the bench"},
  {"番号": 173, "英語": "その事故で負傷する", "日本語": "be injured in the accident"},
  {"番号": 174, "英語": "ウエディングドレスを縫う", "日本語": "sew a wedding dress"},
  {"番号": 175, "英語": "テストの結果", "日本語": "the result of the test"},
  {"番号": 176, "英語": "人類の言語の特徴", "日本語": "features of human language"},
  {"番号": 177, "英語": "現代社会の問題", "日本語": "the problems of modern society"},
  {"番号": 178, "英語": "水車", "日本語": "a water wheel"},
  {"番号": 179, "英語": "教育に高い価値を置く", "日本語": "put a high value on education"},
  {"番号": 180, "英語": "二酸化炭素の温室効果", "日本語": "the greenhouse effect of CO2"},
  {"番号": 181, "英語": "社会の中の個人", "日本語": "individuals in society"},
  {"番号": 182, "英語": "子供に悪い影響を与える", "日本語": "have a bad influence on children"},
  {"番号": 183, "英語": "サービス料を請求する", "日本語": "charge a fee for service"},
  {"番号": 184, "英語": "年40％の割合で", "日本語": "at the rate of 40% a year"},
  {"番号": 185, "英語": "春のきざし", "日本語": "a sign of spring"},
  {"番号": 186, "英語": "水道とガスの事業", "日本語": "water and gas service"},
  {"番号": 187, "英語": "科学技術の進歩", "日本語": "advances in technology"},
  {"番号": 188, "英語": "笑いは最高の良薬だ", "日本語": "Laughter is the best medicine"},
  {"番号": 189, "英語": "新しい物質をつくる", "日本語": "produce new materials"},
  {"番号": 190, "英語": "重工業の中心地", "日本語": "a center of heavy industry"},
  {"番号": 191, "英語": "記録を破ろうとする試み", "日本語": "an attempt to  break the record"},
  {"番号": 192, "英語": "アメリカとフランスの貿易", "日本語": "US trade with France"},
  {"番号": 193, "英語": "君の英語は進歩した", "日本語": "You've made progress in English"},
  {"番号": 194, "英語": "早く帰るための言い訳をする", "日本語": "make an excuse to leave early"},
  {"番号": 195, "英語": "チップを払う習慣", "日本語": "the custom of tipping"},
  {"番号": 196, "英語": "次の一説を読みなさい", "日本語": "Read the following passage"},
  {"番号": 197, "英語": "市場経済", "日本語": "the market economy"},
  {"番号": 198, "英語": "ライオンの足跡", "日本語": "the track of a lion"},
  {"番号": 199, "英語": "公共交通機関を使う", "日本語": "use public transportation"},
  {"番号": 200, "英語": "政府の役人", "日本語": "a government official"},
  {"番号": 201, "英語": "一目ぼれ", "日本語": "love at first sight"},
  {"番号": 202, "英語": "レモンの味", "日本語": "a taste of lemon"},
  {"番号": 203, "英語": "広範囲の情報", "日本語": "a wide range of information"},
  {"番号": 204, "英語": "医者に予約する", "日本語": "make an appointment with the doctor"},
  {"番号": 205, "英語": "医者と患者", "日本語": "a doctor and a patient"},
  {"番号": 206, "英語": "事業計画", "日本語": "a business project"},
  {"番号": 207, "英語": "頼みを聞いてもらえませんか", "日本語": "Would you do me a favor"},
  {"番号": 208, "英語": "外見が違う", "日本語": "differ in appearance"},
  {"番号": 209, "英語": "お金を失う危険を冒す", "日本語": "run the risk of losing money"},
  {"番号": 210, "英語": "仕事のコストと利益", "日本語": "costs and benefits of the business"},
  {"番号": 211, "英語": "ニューヨークの市民", "日本語": "residents of New York"},
  {"番号": 212, "英語": "彼らの親戚と友達", "日本語": "their relatives and friends"},
  {"番号": 213, "英語": "山岳地方", "日本語": "a mountain region"},
  {"番号": 214, "英語": "ユニークな特徴", "日本語": "unique characteristics"},
  {"番号": 215, "英語": "鋭い痛みを感じる", "日本語": "feel a sharp pain"},
  {"番号": 216, "英語": "一組の一卵双生児", "日本語": "a pair of identicial twins"},
  {"番号": 217, "英語": "特別な場合に", "日本語": "on special occasions"},
  {"番号": 218, "英語": "自由貿易の原則", "日本語": "the principle of free trade"},
  {"番号": 219, "英語": "歴史科学", "日本語": "the history department"},
  {"番号": 220, "英語": "君を助けるのが私の義務だ", "日本語": "It is my duty to help you."},
  {"番号": 221, "英語": "事故の現場", "日本語": "the scene of the accident"},
  {"番号": 222, "英語": "彼の理論の科学的根拠", "日本語": "the scientific basis of his theory"},
  {"番号": 223, "英語": "フェアプレーの精神", "日本語": "the spirit of fair play"},
  {"番号": 224, "英語": "コミュニケーションの手段", "日本語": "the medium of communication"},
  {"番号": 225, "英語": "大量生産", "日本語": "mass production"},
  {"番号": 226, "英語": "大勢の観客を集める", "日本語": "gather a large audience"},
  {"番号": 227, "英語": "最も重要な要素", "日本語": "the most important element"},
  {"番号": 228, "英語": "地球規模の気候変動", "日本語": "global climate change"},
  {"番号": 229, "英語": "フランス革命", "日本語": "the French Revolution"},
  {"番号": 230, "英語": "今世紀の最初の4分の1", "日本語": "the first quarter of this century"},
  {"番号": 231, "英語": "家具の少ない部屋", "日本語": "a room with little furniture"},
  {"番号": 232, "英語": "人間の脳", "日本語": "the human brain"},
  {"番号": 233, "英語": "地球の大気中の二酸化炭素", "日本語": "CO2 in the earth's atmosphere"},
  {"番号": 234, "英語": "私有財産", "日本語": "private property"},
  {"番号": 235, "英語": "努力の報酬", "日本語": "a reward for hard work"},
  {"番号": 236, "英語": "国家の安全保障", "日本語": "national security"},
  {"番号": 237, "英語": "喜びの声をあげる", "日本語": "give a cry of delight"},
  {"番号": 238, "英語": "砂漠の人影のない道", "日本語": "a deserted road in the desert"},
  {"番号": 239, "英語": "経歴の違う人々", "日本語": "people from different backgrounds"},
  {"番号": 240, "英語": "少子化の傾向", "日本語": "a trend toward fewer children"},
  {"番号": 241, "英語": "20%の票を得る", "日本語": "get 20% of the vote"},
  {"番号": 242, "英語": "環境に対する悪い影響", "日本語": "a negative impact on the environment"},
  {"番号": 243, "英語": "教育機関", "日本語": "educational institutions"},
  {"番号": 244, "英語": "他人との社会的交流", "日本語": "social interaction with others"},
  {"番号": 245, "英語": "石油の代わりになるもの", "日本語": "an alternative to oil"},
  {"番号": 246, "英語": "子供に害を与えない", "日本語": "do no harm to children"},
  {"番号": 247, "英語": "旅行代理店に行く", "日本語": "go to a travel agency"},
  {"番号": 248, "英語": "すばらしい人間の学習能力", "日本語": "man's great capacity to learn"},
  {"番号": 249, "英語": "イタリアの外務大臣", "日本語": "the Italian foreign minister"},
  {"番号": 250, "英語": "病院で働くボランティア", "日本語": "a hospital volunteer"},
  {"番号": 251, "英語": "インターネットを利用できる", "日本語": "a have access to the Internet"},
  {"番号": 252, "英語": "膨大な量のデータ", "日本語": "large quantities of data"},
  {"番号": 253, "英語": "科学の一分野", "日本語": "a branch of science"},
  {"番号": 254, "英語": "共通の言語", "日本語": "a common language"},
  {"番号": 255, "英語": "大雑把なスケッチ", "日本語": "a rough sketch"},
  {"番号": 256, "英語": "彼が勝つ可能性が高い", "日本語": "He is likely to win."},
  {"番号": 257, "英語": "深刻な社会問題", "日本語": "serious social problems"},
  {"番号": 258, "英語": "特有の性質", "日本語": "a particular character"},
  {"番号": 259, "英語": "みんなが利用できる情報", "日本語": "information available to everyone"},
  {"番号": 260, "英語": "二言語使用の子供たち", "日本語": "bilingual children"},
  {"番号": 261, "英語": "出発の用意ができている", "日本語": "I am ready to start."},
  {"番号": 262, "英語": "正しい答え", "日本語": "the correct answer"},
  {"番号": 263, "英語": "日本の文化にくわしい", "日本語": "be familiar with Japanese culture"},
  {"番号": 264, "英語": "肉体美", "日本語": "physical beauty"},
  {"番号": 265, "英語": "その本は読む価値がある", "日本語": "The book is worth reading."},
  {"番号": 266, "英語": "事故に巻き込まれている", "日本語": "be involved in the accident"},
  {"番号": 267, "英語": "私は素晴らしい時を過ごした", "日本語": "I had a fantastic time"},
  {"番号": 268, "英語": "彼女の私生活", "日本語": "her private life"},
  {"番号": 269, "英語": "明白なまちがい", "日本語": "an obvious mistake"},
  {"番号": 270, "英語": "母語", "日本語": "a native language"},
  {"番号": 271, "英語": "複雑なシステム", "日本語": "a complex system"},
  {"番号": 272, "英語": "喜んで彼女を助けるつもりだ", "日本語": "I am willing to help her."},
  {"番号": 273, "英語": "今日の国際状況", "日本語": "the current international situation"},
  {"番号": 274, "英語": "男性の労働者", "日本語": "male workers"},
  {"番号": 275, "英語": "言葉の適切な使い方", "日本語": "the proper use of words"},
  {"番号": 276, "英語": "彼はその仕事をする能力がある", "日本語": "He is capable of doing the job."},
  {"番号": 277, "英語": "彼は親から独立している。", "日本語": "He is independent 0f his parents."},
  {"番号": 278, "英語": "積極的な考え方", "日本語": "positive thinking"},
  {"番号": 279, "英語": "楽しい経験", "日本語": "a pleasant experience"},
  {"番号": 280, "英語": "重大な違い", "日本語": "a significant difference"},
  {"番号": 281, "英語": "前大統領", "日本語": "the former President"},
  {"番号": 282, "英語": "化学反応", "日本語": "a chemical reaction"},
  {"番号": 283, "英語": "事故で動揺している", "日本語": "be upset by the accident"},
  {"番号": 284, "英語": "前の年から", "日本語": "from the previous year"},
  {"番号": 285, "英語": "冷静でいる", "日本語": "keep calm"},
  {"番号": 286, "英語": "特定の個人", "日本語": "a specific individual"},
  {"番号": 287, "英語": "健康を意識するアメリカ人", "日本語": "health-conscious Americans"},
  {"番号": 288, "英語": "他の人よりすぐれている", "日本語": "be superior to others"},
  {"番号": 289, "英語": "効率のよいエネルギーの使い方", "日本語": "an efficient use of energy"},
  {"番号": 290, "英語": "基本的人権", "日本語": "fundamental human rights"},
  {"番号": 291, "英語": "狭い道", "日本語": "a narrow street"},
  {"番号": 292, "英語": "理にかなった説明", "日本語": "a reasonable explanation"},
  {"番号": 293, "英語": "将来のことで不安になる", "日本語": "feel nervous about the future"},
  {"番号": 294, "英語": "その兄弟は似ている", "日本語": "The brothers look alike."},
  {"番号": 295, "英語": "家庭内暴力", "日本語": "domestic violence"},
  {"番号": 296, "英語": "否定的な答え", "日本語": "a negative answer"},
  {"番号": 297, "英語": "道徳的な判断をする", "日本語": "make a moral judgment"},
  {"番号": 298, "英語": "アメリカ留学を熱望する", "日本語": "be eager to study in the US"},
  {"番号": 299, "英語": "脳のすばらしい能力", "日本語": "the brain's remarkable ability"},
  {"番号": 300, "英語": "悪い霊を追い払う", "日本語": "drive away evil spirits"},
  {"番号": 301, "英語": "夜通し目が覚めている", "日本語": "stay awake all night"},
  {"番号": 302, "英語": "彼の年老いた父母", "日本語": "his aged parents"},
  {"番号": 303, "英語": "君の健康が心配だ", "日本語": "I am anxious about your health."},
  {"番号": 304, "英語": "たくましいボクサー", "日本語": "a tough boxer"},
  {"番号": 305, "英語": "原子力エネルギー", "日本語": "nuclear energy"},
  {"番号": 306, "英語": "イギリスの法律の制度", "日本語": "the British legal system"},
  {"番号": 307, "英語": "何にでも好奇心を持つ", "日本語": "be curious about everything"},
  {"番号": 308, "英語": "市民権", "日本語": "civil rights"},
  {"番号": 309, "英語": "最近の研究によると", "日本語": "according to a recent study"},
  {"番号": 310, "英語": "クラブの先輩の部員", "日本語": "a senior member of the club"},
  {"番号": 311, "英語": "その後すぐ彼は去った", "日本語": "Soon afterward, he left"},
  {"番号": 312, "英語": "30年近く前に", "日本語": "nearly 30 years ago"},
  {"番号": 313, "英語": "その車は小さい。それゆえ、安い。", "日本語": "The car is small and therefore cheap."},
  {"番号": 314, "英語": "ぴったり同時に", "日本語": "at exactly the same time"},
  {"番号": 315, "英語": "ひょっとすると彼は来るかもしれない", "日本語": "He will possibly come."},
  {"番号": 316, "英語": "予想に反して", "日本語": "contrary to expectations"},
  {"番号": 317, "英語": "私はたまに劇場に行く", "日本語": "I occasionally go to the theater."},
  {"番号": 318, "英語": "なぜか寂しい", "日本語": "Somehow I feel lonely."},
  {"番号": 319, "英語": "彼に会うことはめったにない", "日本語": "I seldom see him."},
  {"番号": 320, "英語": "この方が小さく、したがって安い", "日本語": "This is smaller and thus cheaper."},
  {"番号": 321, "英語": "世界中の人々", "日本語": "people throughout the world"},
  {"番号": 322, "英語": "妻と違って私は早起きだ", "日本語": "Unlike my wife, I get up early."},
  {"番号": 323, "英語": "彼は金持ちの上にやさしい", "日本語": "Besides being rich, he is kind."},
  {"番号": 324, "英語": "私の理解をこえている", "日本語": "It's beyond my understanding."},
  {"番号": 325, "英語": "駅から１マイル以内で", "日本語": "within a mile of the station"},
  {"番号": 326, "英語": "時間もお金もない", "日本語": "have neither time nor money"},
  {"番号": 327, "英語": "明日雨が降らない限り出発する", "日本語": "I'll leave tomorrow unless it rains."},
  {"番号": 328, "英語": "日曜以外毎日働く", "日本語": "work every day except Sunday"},
  {"番号": 329, "英語": "君は医者に診てもらうべきだ", "日本語": "You ought to see a doctor"},
  {"番号": 330, "英語": "困難にもかかわらず", "日本語": "in spite of difficulties"},
  {"番号": 331, "英語": "本当かどうかわからない", "日本語": "I don't know whether it is true or not."},
  {"番号": 332, "英語": "彼がなぜ遅れたかを説明する", "日本語": "explain why he was late"},
  {"番号": 333, "英語": "ありのまま真実を受け入れる", "日本語": "accept the truth as it is"},
  {"番号": 334, "英語": "十分な食料を生産する", "日本語": "produce enough food"},
  {"番号": 335, "英語": "神は本当に存在するのか", "日本語": "Does God really exist?"},
  {"番号": 336, "英語": "私の気持ちを表現する", "日本語": "express my feelings"},
  {"番号": 337, "英語": "スープにミルクを加える", "日本語": "add some milk to the soup"},
  {"番号": 338, "英語": "まちがいを犯すのを避ける", "日本語": "avoid making mistakes"},
  {"番号": 339, "英語": "メアリと結婚する", "日本語": "marry Mary"},
  {"番号": 340, "英語": "危険から子どもたちを守る", "日本語": "protect children from danger"},
  {"番号": 341, "英語": "アルコールは脳に影響する", "日本語": "Alcohol affects the brain."},
  {"番号": 342, "英語": "君の未来を決定する", "日本語": "determine your future"},
  {"番号": 343, "英語": "問題を解決する", "日本語": "solve the problem"},
  {"番号": 344, "英語": "野菜はたくさんの水を含んでいる", "日本語": "Vegetables contain a lot of water."},
  {"番号": 345, "英語": "彼とその問題を議論する", "日本語": "discuss the problem with him"},
  {"番号": 346, "英語": "医者の忠告を無視する", "日本語": "ignore the doctor's advice"},
  {"番号": 347, "英語": "彼女の年を推測する", "日本語": "guess how old she is"},
  {"番号": 348, "英語": "円をドルに交換する", "日本語": "exchange yen for dollars"},
  {"番号": 349, "英語": "学生の要求を満たす", "日本語": "satisfy the needs of students"},
  {"番号": 350, "英語": "騒音のことで苦情を言う", "日本語": "complain about the noise"},
  {"番号": 351, "英語": "ついに目標を達成する", "日本語": "finally achieve the goal"},
  {"番号": 352, "英語": "人々の長寿を可能にする", "日本語": "enable people to live longer"},
  {"番号": 353, "英語": "アメリカに住むつもりだ", "日本語": "intend to live in America"},
  {"番号": 354, "英語": "彼に関する情報を得る", "日本語": "obtain information about him"},
  {"番号": 355, "英語": "ケーキを6個に分割する", "日本語": "divide the cake into six pieces"},
  {"番号": 356, "英語": "その音が私をいらだたせる", "日本語": "The noise annoys me."},
  {"番号": 357, "英語": "私の考えは彼女と異なる", "日本語": "My opinion differs from hers."},
  {"番号": 358, "英語": "子供を教育する方法", "日本語": "how to educate children"},
  {"番号": 359, "英語": "友達から本を借りる", "日本語": "borrow a book from a friend"},
  {"番号": 360, "英語": "タイムマシンを発明する", "日本語": "invent a time machine"},
];
